server:
  port: 9093
spring:
  application:
    name: ohagi-app
  cloud:
      config:
        uri: http://localhost:9099
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka,http://localhost:9091/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2