spring:
  profiles:
    active: server1

---
spring:
  profiles: server1
server:
  port: 9090
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
  server:
    eviction-interval-timer-in-ms: 1000

---
spring:
  profiles: server2
server:
  port: 9091
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
  server:
    eviction-interval-timer-in-ms: 1000