server:
  port: 9092
spring:
  application:
    name: man-app
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka,http://localhost:9091/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2